import Head from 'next/head';
import * as React from 'react';

export interface IHeaderProps {
    title: string
}

export default function Header (props: IHeaderProps) {
  return (
      <Head>
        <title>{props.title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
  );
}
