import Head from 'next/head';
import * as React from 'react';
import { usePathname } from "next/navigation";
import { pageRoutes } from '@/redux/constant/page-routes.constant';
export default function Header() {
  var pathName = usePathname();
  Object.keys(pageRoutes).forEach((obj: string) => {
    return (
      (pathName == pageRoutes[obj].route) ?
        pathName = pageRoutes[obj].title : null
    )
  })
  return (
    <Head>
      <title>{pathName}</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
}
